# .streamlit/secrets.toml

supabase_url = "https://imratmpxtoshlacwlgih.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltcmF0bXB4dG9zaGxhY3dsZ2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTI5MDA5MzcsImV4cCI6MjAwODQ3NjkzN30.ihFqud2JO1ltUJgjkvWiZvBk6sjsXm0WgsktvT59q_I"